# Generated by Django 5.1 on 2024-08-08 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brute_Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(default='null', max_length=100)),
                ('investments', models.CharField(default='null', max_length=100)),
                ('stock', models.CharField(default=100, max_length=100)),
                ('inventories', models.CharField(default=100, max_length=100)),
                ('accounts_receivable', models.CharField(default=100, max_length=100)),
                ('fixed_assets', models.IntegerField(default=0)),
                ('other_assets', models.IntegerField(default=0)),
                ('omitted_assets', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fiscal_Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cc', models.IntegerField(default=0, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='null', max_length=100)),
                ('last_name', models.CharField(default='null', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.IntegerField(default=0)),
                ('name', models.CharField(default='null', max_length=100)),
                ('address', models.CharField(default='null', max_length=100)),
                ('telephone', models.IntegerField(default=0)),
                ('mail', models.CharField(default='null', max_length=100)),
                ('extra', models.CharField(default='null', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='null', max_length=100)),
                ('date', models.DateField(default='null')),
                ('description', models.CharField(default='null', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='null')),
                ('liquid_equity', models.IntegerField(default=0)),
                ('heritage_type', models.CharField(default='null', max_length=100)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Pasive_Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_debts', models.IntegerField(default=0)),
                ('business_debts', models.IntegerField(default=0)),
                ('tax_debts', models.IntegerField(default=0)),
                ('other_debts', models.IntegerField(default=0)),
                ('nonexistent_liabilities', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.heritage')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='null', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('fiscal_responsabilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.fiscal_responsibilities')),
            ],
        ),
        migrations.CreateModel(
            name='Rut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(default=0, unique=True)),
                ('check_digit', models.IntegerField(default=0)),
                ('date', models.DateField(default='null')),
                ('rut_type', models.CharField(default='null', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.client')),
            ],
        ),
        migrations.AddField(
            model_name='fiscal_responsibilities',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.rut'),
        ),
        migrations.CreateModel(
            name='Economic_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.rut')),
            ],
        ),
    ]
