# Generated by Django 5.1 on 2024-08-16 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cc', models.IntegerField(default=0, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='null', max_length=100)),
                ('last_name', models.CharField(default='null', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.IntegerField(default=0, unique=True)),
                ('nit', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(default='null', max_length=100)),
                ('address', models.CharField(default='null', max_length=100)),
                ('telephone', models.IntegerField(default=0)),
                ('mail', models.CharField(default='null', max_length=100)),
                ('fiscal_responsibilities', models.BooleanField(default=False)),
                ('extra', models.CharField(default='null', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='tasks.client')),
            ],
        ),
        migrations.CreateModel(
            name='Rut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(default=0, unique=True)),
                ('check_digit', models.IntegerField(default=0)),
                ('primary_economic_activity', models.IntegerField(default=0)),
                ('secondary_economic_activity', models.IntegerField(default=0)),
                ('date', models.DateField(default='null')),
                ('rut_type', models.CharField(default='null', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.client')),
            ],
        ),
    ]
