# Generated by Django 4.1 on 2024-04-15 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brute_Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(default='null', max_length=100)),
                ('investments', models.CharField(default='null', max_length=100)),
                ('stock', models.CharField(default=100, max_length=100)),
                ('inventories', models.CharField(default=100, max_length=100)),
                ('accounts_receivable', models.CharField(default=100, max_length=100)),
                ('fixed_assets', models.IntegerField(default=0)),
                ('other_assets', models.IntegerField(default=0)),
                ('omitted_assets', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='null', max_length=100)),
                ('date', models.DateField(default='null')),
                ('description', models.CharField(default='null', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='null')),
                ('liquid_equity', models.IntegerField(default=0)),
                ('heritage_type', models.CharField(default='null', max_length=100)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Pasive_Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_debts', models.IntegerField(default=0)),
                ('business_debts', models.IntegerField(default=0)),
                ('tax_debts', models.IntegerField(default=0)),
                ('other_debts', models.IntegerField(default=0)),
                ('nonexistent_liabilities', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.heritage')),
            ],
        ),
    ]
