# Generated by Django 5.1 on 2024-08-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(default=0)),
                ('primary_economic_activity', models.IntegerField(default=0)),
                ('previus_year_anticipation', models.IntegerField(default=0)),
                ('next_year_anticipation', models.IntegerField(default=0)),
                ('liquid_heritage', models.IntegerField(default=0)),
                ('liquid_income', models.IntegerField(default=0)),
                ('net_income_tax', models.IntegerField(default=0)),
                ('anual_auditory_benefits', models.CharField(default='null', max_length=100)),
                ('semestrals_auditory_benefits', models.CharField(default='null', max_length=100)),
                ('unearned_income', models.IntegerField(default=0)),
                ('uvt', models.IntegerField(default=0)),
                ('date', models.DateField(default=None)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.client')),
            ],
        ),
        migrations.CreateModel(
            name='Rut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(default=0, unique=True)),
                ('primary_economic_activity', models.IntegerField(default=0)),
                ('secondary_economic_activity', models.IntegerField(default=0)),
                ('date', models.DateField(default='null')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.client')),
            ],
        ),
    ]
